name: AutoShutdown
main: io.github.toastengine.autoshutdown.plugin
version: 1.0.3
description: Timed shutdown of server
author: ToastEngine
commands:
   as:
      description: Provides information about the plugin.
      aliases: [AutoShutdown, autoshutdown]
      permission: AutoShutdown
      default: op
      permission-message: §cYou do not have permission to run that command.
